### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by MrGiaoegg** [Radialbog9/MinecraftManhunt#11]
**Describe the bug**
Text display confusion properly due to encoding errors.

**To Reproduce**
1. Start Minecraft.
2. Input any commands about this plugin.

**Expected behavior**
Save Chinese translation files in GBK encoding.

**Screenshots**
![QQ图片20220630164328](https://user-images.githubusercontent.com/91585367/176634781-395c2d5d-35af-4c06-971e-5c51ed062692.png)

**System Info:**
 - Java 17
 - Minecraft Version 1.18.1
 - Plugin Version 2.1.4-SNAPSHOT

**Comment by TheJoeCoder** [comment]
Hi!
Sorry for the late reply. I've been quite busy lately.
I've added it to the list of things to fix, and I will attempt to fix it tomorrow.

**Comment by TheJoeCoder** [comment]
I have tracked the problem down to Minecraft not interpreting the language file as UTF-8 encoding. I'll fix this within 30 minutes, and I'll make a full release.

**Comment by TheJoeCoder** [comment]
I have fixed this in Radialbog9/MinecraftManhunt@0ea8350cef9f4580d67963a13e9b7f637f24f8e6. A new release will follow.
